### ISSUE TITLE
raw counts instead of cpm

### ISSUE THREAD

**Issue by ailtonpcf** [wbazant/CORRAL#5]
Dear wbazant,

Is it possible to get raw counts instead of cpm? I tried to replace "cpm" by "column" in the parameter 'summaryColumn', but it did not work.

Best regards,
Ailton.

**Comment by wbazant** [comment]
Hi Ailton, thanks for the question! Yes it is, I've updated the documentation in the link below. I'm on my other laptop - could you do me a favour and check that the options I listed all work?

**Comment by ailtonpcf** [comment]
Dear wbazant,

Thank you for the support. All summaryColumn values work.

Bests,
