### ISSUE TITLE
how to use CORRAL with local paired fq.gz data？

### ISSUE THREAD

**Issue by tiantianlili** [wbazant/CORRAL#7]
Hi! Thanks for your wonderful pipline! 
I am new in using workflow, so I am confuse in how to use CORRAL to quantify euk in my local paired fq.gz data.
I have download nextflow and marker_alignments successfully. marker_alignments  could work using .bam or .sam as input successfully. But I want use many paired fq.gz metagenome data as input (located in the same folder), I don‘t know how to use the nextflow, and I can't find the cluster.conf you mentioned in "executing environment". 
Please help me as title described, I would be appreciate for your help!

**Comment by wbazant** [comment]
Hi, thank you for your interest in the pipeline! I changed the README.md a bit. For your run, I think you will want the parameters `--downloadMethod local` and `--libraryLayout paired`, and no `--unpackMethod`. 

 Could you try to make a file like [run.sh](https://github.com/wbazant/CORRAL#runsh), together with `in.tsv` and `resource_configuration.conf`? You can substitute your parameters, or try the example ones first, and let me know if it worked.

**Comment by tiantianlili** [comment]
Thanks for your help! CORRAL worked successfully！
But I noticed one new file named "work" was been created in my work path, could I avoid this "work" file creation? I'm worried it'll take up a lot of storage space due to my lots of samples.
And a little suggestion is that if the marker_alignments, nextflow, run.sh and resource_configuration.conf could be integrated together (maybe in conda?)，that will be more convenient.

"work" file like this (copperA186 was my sample name):
`$ ls /media/ubuntu/data/tianli/biosoft/CORRAL/work -R
/media/ubuntu/data/tianli/biosoft/CORRAL/work:
63  99  d2  f5

/media/ubuntu/data/tianli/biosoft/CORRAL/work/63:
04d5a4d568f5bac6d5c5edad3287cb

/media/ubuntu/data/tianli/biosoft/CORRAL/work/63/04d5a4d568f5bac6d5c5edad3287cb:
alignmentsPaired.sam  copperA186_350.fq_1.gz  copperA186_350.fq_2.gz  numReads.txt

/media/ubuntu/data/tianli/biosoft/CORRAL/work/99:
eb321bb539eb249a376313c5fca578

/media/ubuntu/data/tianli/biosoft/CORRAL/work/99/eb321bb539eb249a376313c5fca578:

/media/ubuntu/data/tianli/biosoft/CORRAL/work/d2:
73a9610937783cf9177c48d4a98c25

/media/ubuntu/data/tianli/biosoft/CORRAL/work/d2/73a9610937783cf9177c48d4a98c25:
alignmentsPaired.sam  copperA186.taxa.tsv  numReads.txt

/media/ubuntu/data/tianli/biosoft/CORRAL/work/f5:
315dc1c21c04db164a2dc5b3092bf2

/media/ubuntu/data/tianli/biosoft/CORRAL/work/f5/315dc1c21c04db164a2dc5b3092bf2:
alignmentsPaired.sam  copperA186.alignmentStats.txt  numReads.txt`

**Comment by wbazant** [comment]
That's great, I hope you find some eukaryotes in the samples!

Nextflow makes the `work` directory structure, and you might want to keep this folder at least for a while - if the results in `copperA186.taxa.tsv` don't seem right, we'll be able to examine the alignment evidence in the `alignmentsPaired.sam` file next to it.

There shouldn't be any big files in there - if the pipeline works as I remember, the big `fq` files are not copied into it, but linked. But if it's not, you can `find work -type f -name '*.gz -delete' .
